### PR TITLE
Creating multiple figure papers for 3D tracking

### PR DESCRIPTION
**Pull request by chrisdembia**
This change is [Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/9)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
Didn't do a super thorough review, but LGTM. Just one minor thing that you could update.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/9#-:-M38OQgvDxNY3felaN-t:b-y0ls02)* status: all files reviewed, 2 unresolved discussions (waiting on @chrisdembia)

___
*[code/tracking_walking.py, line 54 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/9#-M38NA6eCRJbT0wMS6tR:-M38NA6f9-z-53R3L5lb:blzxddu) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/5e35c1cf0b81a1032cbe3c1493e12aaf06a406e6/code/tracking_walking.py#L54)):*
> ```Python
>             tracking_weight=10,
>             effort_weight=10,
>             color=cm.get_cmap(self.cmap)(0.5),
> ```

You already saved the cmap to a variable above.
___
*[code/utilities.py, line 217 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/9#-M38OCsw1WLAglSCh_Mp:-M38OCsx694Qmqf0G485:b-ks4v30) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/5e35c1cf0b81a1032cbe3c1493e12aaf06a406e6/code/utilities.py#L217)):*
> ```Python
>     return shifted_time, shifted_ordinate
> 
> def calc_net_generalized_forces(model, moco_traj):
> ```

This would be a useful Moco utility too. Would open the door to joint moment tracking.

**Review by nickbianco — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/9#-:-M38Odvm9rbrKP2BkHsN:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @chrisdembia)

**Review by chrisdembia — COMMENTED** [review]
Ready for review.

> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/9#-:-M3Cz-GQ1q8mZqoO2O6-:b8pt725)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[code/tracking_walking.py, line 54 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/9#-M38NA6eCRJbT0wMS6tR:-M3Cyquw5RILpFMUDeuI:b-896fix) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/5e35c1cf0b81a1032cbe3c1493e12aaf06a406e6/code/tracking_walking.py#L54)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

You already saved the cmap to a variable above.
</blockquote></details>

Done.
___
*[code/utilities.py, line 217 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/9#-M38OCsw1WLAglSCh_Mp:-M3Cyr_-A8SGIFM3gJdz:b3hfd77) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/5e35c1cf0b81a1032cbe3c1493e12aaf06a406e6/code/utilities.py#L217)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This would be a useful Moco utility too. Would open the door to joint moment tracking.
</blockquote></details>

Good point! Maybe prototyping utilities in scripting before moving them into C++ is a good workflow.

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/9#-:-M3DeBK-B2yQM1s1F_Ps:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
