### PR TITLE
Moco paper appendix Carmichael comments

### PR DESCRIPTION
**Pull request by chrisdembia**
This change is [Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/10)

### CODE REVIEW

**Comment by chrisdembia** [comment]
I'm not really satisfied with my changes to the description of the velocity correction. Can we chat about this tomorrow?

**Comment by nickbianco** [comment]
@chrisdembia This is ready for review. I'm not sure why the abstract for that new reference is getting diffed.

**Comment by nickbianco** [comment]
Ready for review.

**Comment by nickbianco** [comment]
@chrisdembia 
noice

**Pull request merged**
