### PR TITLE
Add 3D tracking example

### PR DESCRIPTION
**Pull request by nickbianco**
This PR adds an example that tracks experimental data with a 3D model with ground contact. The example also includes results where minimizing control effort is favor equally and more than tracking data in the cost function.

A draft of a potential paper figure is below. Still some small things to investigate (e.g. why is hip flexion tracking poorly in the "track" condition?).

motion_tracking_walking

---
This change is [Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4)

### CODE REVIEW

**Review by chrisdembia — CHANGES_REQUESTED** [review]
Yay! I gave a quick look. I still want to read the code in more depth and run it locally. I really like the figure.

How did you choose to plot stride time? What about plotting effort instead?

> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-:-LvInbsn1L-DB7fKScmX:b-kl7lov)* status: 6 of 9 files reviewed, 6 unresolved discussions (waiting on @chrisdembia and @nickbianco)

___
*[code/prescribed_walking.py, line 605 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIlrbsEqAshtNQ9iL1:-LvIlrbsEqAshtNQ9iL2:b-jarwc9) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/prescribed_walking.py#L605)):*
> ```Python
>                                         mocoinverse_jr_solution_file % root_dir)
>             report.generate()
> ```

Is this file basically unchanged other than renaming?
___
*[code/tracking_walking.py, line 20 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvImEHxBDi-JHXQL_jU:-LvImEHy7m3iTdePy62X:bajn6u0) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L20)):*
> ```Python
>         self.final_time = 1.96
>         self.grf_index = [1620, 3921]
>         self.coord_index = [81, 197]
> ```

Can we avoid hardcoding these indices?
___
*[code/tracking_walking.py, line 41 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIm_bg9RS4FSP1ZhFW:-LvIm_bg9RS4FSP1ZhFX:b14j0qe) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L41)):*
> ```Python
>             model = osim.Model(os.path.join(root_dir,
>                 'resources/Rajagopal2016/'
>                 'subject_walk_armless_contact_bounded_lumbar_80musc.osim'))
> ```

Can you add comments describing the difference between the models? I would prefer that we programmatically generate one from the other. Actually, ideally, we do not add any more model files, and we programmatically generate both of these.
___
*[code/tracking_walking.py, line 218 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvInRVD-nbzQyL-ltwE:-LvInRVD-nbzQyL-ltwF:b65bjh1) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L218)):*
> ```Python
>         distanceConstraint.addFramePair(osim.MocoMinimumDistanceConstraintPair(
>             '/bodyset/toes_l', '/bodyset/calcn_r', distance))
>         problem.addPathConstraint(distanceConstraint)
> ```

What happens if you use this constraint to generate an initial guess and then solve a problem without this constraint? Do the legs still cross?
___
*[code/tracking_walking.py, line 292 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIn6x82PwAFhQsQsgM:-LvIn6x82PwAFhQsQsgN:b-i5zy2b) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L292)):*
> ```Python
>         solver.set_minimize_implicit_multibody_accelerations(True)
>         solver.set_implicit_multibody_accelerations_weight(
>             0.0001 / model.getNumCoordinates())
> ```

What's the rationale for dividing by this number?
___
*[results/motion_tracking_walking_cmc_results/README.md, line 0 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIlGbG1v0vMq8vdR5z:-LvIlGbG1v0vMq8vdR6-:bu507by) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/results/motion_tracking_walking_cmc_results/README.md#L0)):*
I think I created this README so that we could gitignore the files inside this directory (because you cannot commit directories, only files). Is the CMC results folder gone now?

**Comment by chrisdembia** [comment]
The match in GRF is pretty astounding, considering we are not tracking GRF.

**Review by chrisdembia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4)* status: 6 of 9 files reviewed, 7 unresolved discussions (waiting on @chrisdembia and @nickbianco)

___
*[code/tracking_walking.py, line 499 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIyAFG7mJF1ehIISpf:-LvIyAFH7XO5nGyM9lGy:b-5tnun8) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L499)):*
> ```Python
>                     '/jointset/ankle_l/ankle_angle_l/value'), color=color, 
>                     lw=lw)
>             ax_ankle.set_ylabel('ankle dorsiflexion (degree)')
> ```

`(degrees)` everywhere, for consistency.

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4)* status: 6 of 9 files reviewed, 7 unresolved discussions (waiting on @chrisdembia)

___
*[code/prescribed_walking.py, line 605 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIlrbsEqAshtNQ9iL1:-LvNDuR45l0vMUVmNFOe:bb77ufg) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/prescribed_walking.py#L605)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Is this file basically unchanged other than renaming?
</blockquote></details>

Yes.
___
*[code/tracking_walking.py, line 20 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvImEHxBDi-JHXQL_jU:-LvNDz4QBfjFCriuQfv-:bofl4nv) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L20)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Can we avoid hardcoding these indices?
</blockquote></details>

Yep, can do. I just wanted to get a figure created by yesterday.
___
*[code/tracking_walking.py, line 41 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIm_bg9RS4FSP1ZhFW:-LvNMGrB-_WK90zElQ0B:b-waqau9) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L41)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Can you add comments describing the difference between the models? I would prefer that we programmatically generate one from the other. Actually, ideally, we do not add any more model files, and we programmatically generate both of these.
</blockquote></details>

Will make changes, as discussed in person.
___
*[code/tracking_walking.py, line 218 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvInRVD-nbzQyL-ltwE:-LvNE4ds1TJgtIpGvrr1:blt7i51) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L218)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

What happens if you use this constraint to generate an initial guess and then solve a problem without this constraint? Do the legs still cross?
</blockquote></details>

I discussed in person, I will try editing the tracking problem weights and see if the problem persists.
___
*[code/tracking_walking.py, line 292 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIn6x82PwAFhQsQsgM:-LvNE9LhEtJkmUZR_tao:b-4dzb31) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L292)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

What's the rationale for dividing by this number?
</blockquote></details>

This I mostly got from trial and error. I like that it is an order of magnitude lower than the the lowest tracking or effort weight.
___
*[code/tracking_walking.py, line 499 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIyAFG7mJF1ehIISpf:-LvNMdiH4mrM8oWvUSny:b-896fix) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L499)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

`(degrees)` everywhere, for consistency.
</blockquote></details>

Done.
___
*[results/motion_tracking_walking_cmc_results/README.md, line  at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIlGbG1v0vMq8vdR5z:-LvNN-o9204-yZvx6dqm:b-56k46p) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/results/motion_tracking_walking_cmc_results/README.md#L)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

I think I created this README so that we could gitignore the files inside this directory (because you cannot commit directories, only files). Is the CMC results folder gone now?
</blockquote></details>

The folder and file are still there in my local repo, and the gitignore looks correct. I'm not sure what's wrong.

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4)* status: 6 of 9 files reviewed, 7 unresolved discussions (waiting on @chrisdembia)

___
*[results/motion_tracking_walking_cmc_results/README.md, line  at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIlGbG1v0vMq8vdR5z:-LvNQGUBE1uAQZt-UMKb:bouz6nu) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/results/motion_tracking_walking_cmc_results/README.md#L)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

The folder and file are still there in my local repo, and the gitignore looks correct. I'm not sure what's wrong.
</blockquote></details>

Ah, it's because I renamed this folder to `motion_prescribed_walking_cmc_results`.

**Review by chrisdembia — CHANGES_REQUESTED** [review]
I skimmed the rest of this pretty quickly. It's amazing how clean this code is, given what it's doing.

After reducing the number of model files, feel free to merge.

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-:-LvSTIno7HTaUV6DmB_o:b-sbaj06)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @chrisdembia and @nickbianco)

___
*[code/tracking_walking.py, line 292 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIn6x82PwAFhQsQsgM:-LvSSY6T-cF2TEHcbWbp:b-5trtlt) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L292)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This I mostly got from trial and error. I like that it is an order of magnitude lower than the the lowest tracking or effort weight.
</blockquote></details>

Do you think dividing by num coordinates should be baked into the solver?

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4)* status: 7 of 13 files reviewed, 3 unresolved discussions (waiting on @chrisdembia)

___
*[code/tracking_walking.py, line 292 at r1](https://reviewable.io/reviews/stanfordnmbl/mocopaper/4#-LvIn6x82PwAFhQsQsgM:-LyBGy5W6MzgxpVMF-tI:b9sh0ua) ([raw file](https://github.com/stanfordnmbl/mocopaper/blob/b6b74d285886bf1b2d0f9e734ebd89f3bdc3d915/code/tracking_walking.py#L292)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Do you think dividing by num coordinates should be baked into the solver?
</blockquote></details>

It could be, it's a common normalization that Ton and Antoine do.

**Pull request merged**
